name: services | traefik | update-proxy-config

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "services/traefik/rules/**"
      - "services/traefik/authelia/access_control.yaml"
      - "services/traefik/authelia/configuration.yml"
      - "services/traefik/crowdsec/acquis.yaml"
      - "services/traefik/routes.yaml"
      - "services/traefik/docker-compose.yaml"
  workflow_dispatch:

jobs:
  update-traefik:
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: traefik
      playbook: services/traefik/ansible/traefik-update.yaml
    secrets: inherit
    