[lxc_template]
lxc ansible_host={{ POSTGRES17_IP }} ansible_user=root

[pve_host]
pve ansible_host={{ PVE_NODE_IP }} ansible_user=root

[pve_host:vars]
vmid={{ POSTGRES17_VMID }}
template_name=postgres17-debian12
templates_dir={{ TEMPLATES_DIR }}