[lxc_template]
lxc ansible_host=10.1.1.250 ansible_user=root

#would change or parameterize - top level .env stuff
[pve_host]
pve ansible_host=10.1.1.54 ansible_user=root

[pve_host:vars]
vmid=999
template_name=postgres17-debian12
templates_dir=/mnt/pve/truenas/template/cache