name: "Normalize AWS environment variables"
description: "Normalize prod/dev secrets & vars into canonical AWS_* env vars"

inputs:
  secrets_json:
    required: true
    description: "All secrets as JSON (use toJson(secrets))"
  vars_json:
    required: true
    description: "All vars as JSON (use toJson(vars))"

runs:
  using: "composite"
  steps:
    - name: Normalize AWS vars/secrets
      shell: bash
      run: |
        SECRETS='${{ inputs.secrets_json }}'
        VARS='${{ inputs.vars_json }}'

        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "AWS_TF_BACKEND_BUCKET=$(echo "$VARS" | jq -r '.AWS_TF_BACKEND_BUCKET')" >> $GITHUB_ENV
        else
          echo "AWS_TF_BACKEND_BUCKET=$(echo "$VARS" | jq -r '.AWS_TF_BACKEND_BUCKET_DEV')" >> $GITHUB_ENV
        fi
