name: Docker LXC template CI/CD

on:
  push:
    branches:
      - main
      - "feature/**"
    paths:
      - "ansible/lxc/arr.yaml"
      - "terraform/modules/lxc/**"
      - ".gitea/workflows/arr-lxc.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/lxc.yaml
    with:
      lxc_name: arr
      vmid: 301
      ip: "10.1.1.20"
      ostemplate: truenas:vztmpl/docker-debian12.tar.zst
      memory: 2048
      cores: 1
      storage_size: "16G"
      enable_docker: true
      unprivileged: true
    secrets: inherit