name: Select Environment Variables

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch name to decide env (main = prod, else dev)"
        required: true
        type: string
    secrets:
      PVE_USER:
        required: false
      PVE_PASSWORD:
        required: false
      DEV_PVE_USER:
        required: false
      DEV_PVE_PASSWORD:
        required: false
    outputs:
      pm_user:
        value: ${{ jobs.resolve.outputs.pm_user }}
      pm_password:
        value: ${{ jobs.resolve.outputs.pm_password }}
      pm_disk_storage:
        value: ${{ jobs.resolve.outputs.pm_disk_storage }}
      pm_node_name:
        value: ${{ jobs.resolve.outputs.pm_node_name }}
      pm_api_url:
        value: ${{ jobs.resolve.outputs.pm_api_url }}
      pm_node_ip:
        value: ${{ jobs.resolve.outputs.pm_node_ip }}
  workflow_dispatch:

jobs:
  resolve:
    runs-on: ubuntu-latest
    outputs:
      pm_user: ${{ steps.set-vars.outputs.pm_user }}
      pm_password: ${{ steps.set-vars.outputs.pm_password }}
      pm_disk_storage: ${{ steps.set-vars.outputs.pm_disk_storage }}
      pm_node_name: ${{ steps.set-vars.outputs.pm_node_name }}
      pm_api_url: ${{ steps.set-vars.outputs.pm_api_url }}
      pm_node_ip: ${{ steps.set-vars.outputs.pm_node_ip }}
    steps:
      - id: set-vars
        run: |
          if [ "${{ inputs.branch }}" = "main" ]; then
            echo "pm_user=${{ secrets.PVE_USER }}" >> $GITHUB_OUTPUT
            echo "pm_password=${{ secrets.PVE_PASSWORD }}" >> $GITHUB_OUTPUT
            echo "pm_disk_storage=${{ vars.PVE_DISK_STORAGE }}" >> $GITHUB_OUTPUT
            echo "pm_node_name=${{ vars.PVE_NODE_NAME }}" >> $GITHUB_OUTPUT
            echo "pm_api_url=${{ vars.PVE_API_URL }}" >> $GITHUB_OUTPUT
            echo "pm_node_ip=${{ vars.PVE_NODE_IP }}" >> $GITHUB_OUTPUT
          else
            echo "pm_user=${{ secrets.DEV_PVE_USER }}" >> $GITHUB_OUTPUT
            echo "pm_password=${{ secrets.DEV_PVE_PASSWORD }}" >> $GITHUB_OUTPUT
            echo "pm_disk_storage=${{ vars.DEV_PVE_DISK_STORAGE }}" >> $GITHUB_OUTPUT
            echo "pm_node_name=${{ vars.DEV_PVE_NODE_NAME }}" >> $GITHUB_OUTPUT
            echo "pm_api_url=${{ vars.DEV_PVE_API_URL }}" >> $GITHUB_OUTPUT
            echo "pm_node_ip=${{ vars.DEV_PVE_NODE_IP }}" >> $GITHUB_OUTPUT
          fi
