name: Deploy LXC template

on:
  workflow_call:
    inputs:
      working-dir:
        description: "Directory for Terraform + Ansible"
        required: true
        type: string
      playbook:
        description: "Ansible playbook file"
        required: true
        type: string
      template-name:
        description: "Name for LXC template"
        required: true
        type: string
      lxc-name:
        description: "Name of the lxc to look up"
        required: true
        type: string
    secrets: inherit

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/gitea-runner-tools:latest

    defaults:
      run:
        working-directory: ${{ inputs.working-dir }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Render main.tf
        run: |
          python3 ../../../utils/render.py

      - name: Create credentials.auto.tfvars
        run: |
          cat > credentials.auto.tfvars <<EOF
          pm_user         = "${{ secrets.PVE_USER }}"
          pm_password     = "${{ secrets.PVE_PASSWORD }}"
          lxc_password    = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key  = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          EOF

      - name: Create vars.auto.tfvars
        run: |
          cat > vars.auto.tfvars <<EOF
          pm_node_name    = "${{ vars.PVE_NODE_NAME }}"
          pm_api_url      = "${{ vars.PVE_API_URL }}"
          EOF

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        id: tfout
        run: terraform apply -input=false -auto-approve tfplan

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MASTER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.PVE_NODE_IP }} >> ~/.ssh/known_hosts
      
      - name: Lookup VMID and IP for the target VM
        id: lookup
        run: |
          sleep 15
          # Lookup VMID
          VMID=$(ssh -oBatchMode=yes root@${{ vars.PVE_NODE_IP }} \
            "pvesh get /cluster/resources --type vm --output-format yaml \
            | awk '/name:[[:space:]]*${{ inputs.lxc-name }}/ {found=1} found && /vmid:/ {print \$2; exit}'")
          
          if [ -z "$VMID" ]; then
            echo "ERROR: VMID not found for ${{ inputs.lxc-name }}"
            exit 1
          fi

          # Lookup IP
          IP=$(ssh -oBatchMode=yes root@${{ vars.PVE_NODE_IP }} \
            "pct exec $VMID ip addr show | grep -oP '(?<=inet )10\.1\.1\.\d+'")

          echo "LXC_VMID=$VMID" >> $GITHUB_ENV
          echo "LXC_IP=$IP" >> $GITHUB_ENV


      - name: Render hosts.ini
        run: |
          cat > hosts.ini <<EOF
          [lxc_template]
          lxc ansible_host=${LXC_IP} ansible_user=root

          [pve_host]
          pve ansible_host=${{ vars.PVE_NODE_IP }} ansible_user=root

          [pve_host:vars]
          vmid=${LXC_VMID}
          template_name=${{ inputs.template-name }}
          templates_dir=${{ vars.TEMPLATES_DIR }}
          EOF

      - name: debug hosts.ini
        run: cat hosts.ini

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: ../../../ansible/ansible.cfg
        run: ansible-playbook -i hosts.ini ${{ inputs.playbook }}

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -auto-approve -input=false
