name: Deploy LXC template

on:
  workflow_call:
    inputs:
      template-name:
        description: "Name for LXC template"
        required: true
        type: string
      lxc_name:
        description: "Name of the lxc to look up"
        required: true
        type: string
      ostemplate:
        description: "location of the base os template"
        required: true
        type: string
      unprivileged:
        description: "should lxc be unprivileged"
        required: true
        type: string
    secrets: inherit

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/gitea-runner-tools:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create credentials.auto.tfvars
        run: |
          cat > terraform/modules/lxc/credentials.auto.tfvars <<EOF
          pm_user         = "${{ secrets.PVE_USER }}"
          pm_password     = "${{ secrets.PVE_PASSWORD }}"
          lxc_password    = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key  = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          EOF

      - name: Create vars.auto.tfvars
        #note the lack of quotes around the unprivileged bool
        run: |
          cat > terraform/modules/lxc/vars.auto.tfvars <<EOF
          gateway         = "${{ vars.GATEWAY }}"
          storage         = "${{ vars.PVE_DISK_STORAGE }}"
          ostemplate      = "${{ inputs.ostemplate }}"
          hostname        = "${{ inputs.lxc_name }}"
          unprivileged    = ${{ inputs.unprivileged }}
          pm_node_name    = "${{ vars.PVE_NODE_NAME }}"
          pm_api_url      = "${{ vars.PVE_API_URL }}"
          EOF

      - name: Terraform Init
        run: terraform -chdir=terraform/modules/lxc init -input=false

      - name: Terraform Plan
        run: terraform -chdir=terraform/modules/lxc plan -out=tfplan -input=false

      - name: Terraform Apply
        if: ${{ github.ref_name == 'main' }}
        id: tfout
        run: terraform -chdir=terraform/modules/lxc apply -input=false -auto-approve tfplan

  ansible:
    #add new runner tag "prod"
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/debian-latest-ansible:nightly

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MASTER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.PVE_NODE_IP }} >> ~/.ssh/known_hosts
      
      - name: Lookup VMID and IP for the target LXC
        if: ${{ github.ref_name == 'main' }}
        run: |
          sleep 15
          # Lookup VMID
          VMID=$(ssh -oBatchMode=yes root@${{ vars.PVE_NODE_IP }} \
            "pvesh get /cluster/resources --type vm --output-format yaml \
            | awk -v target='${{ inputs.lxc_name }}' '
                /^[[:space:]]*name:/ {
                  split(\$0, a, \": \")
                  if (a[2] == target) found=1
                }
                found && /^[[:space:]]*vmid:/ {print \$2; exit}'")

          if [ -z "$VMID" ]; then
            echo "ERROR: VMID not found for ${{ inputs.lxc_name }}"
            exit 1
          fi

          # Lookup IP
          IP=$(ssh -oBatchMode=yes root@${{ vars.PVE_NODE_IP }} \
            "pct exec $VMID ip addr show | grep -oP '(?<=inet )10\.1\.1\.\d+'")

          echo "LXC_VMID=$VMID" >> $GITHUB_ENV
          echo "LXC_IP=$IP" >> $GITHUB_ENV
          echo "ANSIBLE_CONNECTION=ssh" >> $GITHUB_ENV

      - name: Set test ansible target
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo "LXC_IP=localhost" >> $GITHUB_ENV
          echo "ANSIBLE_CONNECTION=local" >> $GITHUB_ENV

      - name: Render hosts.ini
        run: |
          cat > hosts.ini <<EOF
          [lxc_template]
          lxc ansible_host=${LXC_IP} ansible_user=root ansible_connection=${ANSIBLE_CONNECTION}

          [pve_host]
          pve ansible_host=${{ vars.PVE_NODE_IP }} ansible_user=root

          [pve_host:vars]
          vmid=${LXC_VMID}
          template_name=${{ inputs.template-name }}
          templates_dir=${{ vars.TEMPLATES_DIR }}
          EOF

      - name: debug hosts.ini
        run: cat hosts.ini

      - name: inject ansible pve task
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "\n- import_playbook: ../common/dump-lxc-to-template.yaml" >> ansible/lxc-template/${{ inputs.lxc_name }}-template.yaml

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: ansible-playbook -i hosts.ini ansible/lxc-template/${{ inputs.lxc_name }}-template.yaml

  cleanup:
    if: ${{ github.ref_name == 'main' }}
    #add new runner tag "prod"
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/gitea-runner-tools:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Create credentials.auto.tfvars
        run: |
          cat > terraform/modules/lxc/credentials.auto.tfvars <<EOF
          pm_user         = "${{ secrets.PVE_USER }}"
          pm_password     = "${{ secrets.PVE_PASSWORD }}"
          lxc_password    = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key  = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          EOF

      - name: Create vars.auto.tfvars
        #note the lack of quotes around the unprivileged bool
        run: |
          cat > terraform/modules/lxc/vars.auto.tfvars <<EOF
          gateway         = "${{ vars.GATEWAY }}"
          storage         = "${{ vars.PVE_DISK_STORAGE }}"
          ostemplate      = "${{ inputs.ostemplate }}"
          hostname        = "${{ inputs.lxc_name }}"
          unprivileged    = ${{ inputs.unprivileged }}
          pm_node_name    = "${{ vars.PVE_NODE_NAME }}"
          pm_api_url      = "${{ vars.PVE_API_URL }}"
          EOF
        
      - name: Terraform Destroy
        run: |
          terraform -chdir=terraform/modules/lxc init -input=false
          terraform -chdir=terraform/modules/lxc destroy -auto-approve -input=false
