name: Deploy LXC

on:
  workflow_call:
    inputs:
      lxc_name:
        description: "Name of the lxc to look up"
        required: true
        type: string
      ostemplate:
        description: "location of the base os template"
        required: true
        type: string
      vmid:
        description: "vmid for the LXC"
        required: true
        type: string
      memory:
        description: "memory for the LXC in MB"
        required: true
        type: string
      cores:
        description: "number of cores for LXC"
        required: true
        type: string
      storage_size:
        description: "size of LXC disk"
        required: true
        type: string
      ip:
        description: "ip addres for LXC"
        required: true
        type: string
      enable_docker:
        description: "enable keyctl and nesting for docker"
        required: true
        type: string
      unprivileged:
        description: "should lxc be unprivileged"
        required: true
        type: string
    secrets: inherit

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/gitea-runner-tools:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create credentials.auto.tfvars
        run: |
          cat > terraform/credentials.auto.tfvars <<EOF
          pm_user         = "${{ secrets.PVE_USER }}"
          pm_password     = "${{ secrets.PVE_PASSWORD }}"
          lxc_password    = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key  = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          EOF

      - name: Create vars.auto.tfvars
        #note the lack of quotes around the unprivileged bool
        run: |
          cat > terraform/vars.auto.tfvars <<EOF
          gateway         = "${{ vars.GATEWAY }}"
          storage         = "${{ vars.PVE_DISK_STORAGE }}"
          ostemplate      = "${{ inputs.ostemplate }}"
          memory          = "${{ inputs.memory }}"
          cores           = "${{ inputs.cores }}"
          storage_size    = "${{ inputs.storage_size }}"
          ip              = "${{ inputs.ip }}"
          enable_docker   = "${{ inputs.enable_docker }}"
          hostname        = "${{ inputs.lxc_name }}"
          unprivileged    = ${{ inputs.unprivileged }}
          pm_node_name    = "${{ vars.PVE_NODE_NAME }}"
          pm_api_url      = "${{ vars.PVE_API_URL }}"
          EOF

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        if: github.ref_name == 'refs/heads/main'
        id: tfout
        run: terraform -chdir=terraform apply -input=false -auto-approve tfplan

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MASTER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.PVE_NODE_IP }} >> ~/.ssh/known_hosts

      - name: Render hosts.ini
        run: |
          cat > hosts.ini <<EOF
          [lxc_template]
          lxc ansible_host=${{ inputs.ip }} ansible_user=root

          [pve_host]
          pve ansible_host=${{ vars.PVE_NODE_IP }} ansible_user=root

          [pve_host:vars]
          vmid=${{ inputs.vmid }}
          EOF

      - name: debug hosts.ini
        run: cat hosts.ini

      - name: Run Ansible Playbook
        if: ${{ github.ref_name }} == 'refs/heads/main'
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: ansible-playbook -i hosts.ini ansible/lxc/${{ inputs.lxc_name }}.yaml
