name: Main infrastructure CI/CD

on:
  push:
    branches:
      - main
      - "feature/**"
    paths:
      - "terraform/**"
      - ".gitea/workflows/arr-lxc.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/gitea-runner-tools:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create credentials.auto.tfvars
        run: |
          cat > terraform/credentials.auto.tfvars <<EOF
          pm_user         = "${{ secrets.PVE_USER }}"
          pm_password     = "${{ secrets.PVE_PASSWORD }}"
          lxc_password    = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key  = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          EOF
      
      - name: Generate backend.tfvars from repo vars
        run: |
          REPO_NAME=$(echo "${GITEA_REPOSITORY}" | cut -d'/' -f2)
          cat > terraform/backend.tfvars <<EOF
          bucket = "${{ vars.AWS_TF_BACKEND_BUCKET }}"
          key    = "${REPO_NAME}"
          region = "${{ vars.AWS_REGION }}"
          EOF

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false -backend-config=backend.tfvars

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan -input=false -backend-config=backend.tfvars

      - name: Terraform Apply
        id: tfout
        run: terraform -chdir=terraform apply -input=false -auto-approve -backend-config=backend.tfvars tfplan