name: Postgres17 LXC template CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "ansible/lxc-template/postgres17-template.yaml"
      - "terraform/modules/lxc-template/**"
      - ".gitea/workflows/postgres17-template.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/lxc-template.yaml
    with:
      lxc_name: postgres17
      template-name: postgres17-debian12
      ostemplate: truenas:vztmpl/debian-12-standard_12.12-1_amd64.tar.zst
      unprivileged: true
    secrets: inherit
