name: Postgres17 LXC template CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "LXC/templates/Postgres17/**"
      - "terraform/modules/lxc-template/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/lxc-template.yaml
    with:
      working-dir: LXC/templates/Postgres17
      playbook: Postgres17.yaml
    secrets: inherit
