name: Postgres17 LXC template CI/CD

on:
  push:
    branches:
      - main
    paths:
    #would change
      - "LXC/templates/Postgres17/**"
      - "terraform/modules/lxc-template/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/gitea-runner-tools:latest

    defaults:
      run:
      #would change
        working-directory: LXC/templates/Postgres17

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create credentials.auto.tfvars
        run: |
          cat > credentials.auto.tfvars <<EOF
          pm_api_url            = "${{ secrets.PVE_API_URL }}"
          pm_user               = "${{ secrets.PVE_USER }}"
          pm_password   = "${{ secrets.PVE_PASSWORD }}"
          lxc_password          = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key        = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          EOF

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        id: tfout
        run: terraform apply -input=false -auto-approve tfplan

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MASTER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: sleep to allow lxc to come online
        run: |
            sleep 30

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: ../../../ansible/ansible.cfg
        #would change
        run: ansible-playbook -i hosts.ini Postgres17.yaml

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -auto-approve -input=false
