name: test CI/CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: git.arasmith.org/admin/gitea-runner-tools:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: dump
        run: ${{ toJson(secrets) }}
        shell: mv {0} secrets.json
      
      - name: read
        run: cat secrets.json