name: common | lxc-migration

on:
  workflow_call:
    inputs:
      lxc_name:
        description: "Name of the lxc to migrate to"
        required: true
        type: string
      playbook:
        description: "Absolute path to the ansible playbook to run"
        required: true
        type: string
      source_host:
        description: "IP address or domain name of migration source"
        required: true
        type: string
      source_user:
        description: "User who owns the data to be migrated"
        required: true
        type: string
    secrets: inherit

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: ./.gitea/actions/setup-ssh
        with:
          ssh_private_key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}

      - name: Add migration source to known hosts
        run: ssh-keyscan -H ${{ inputs.source_host }} >> ~/.ssh/known_hosts

      - name: Lookup LXC VMID and node
        uses: ./.gitea/actions/lookup-lxc-vmid-node
        with:
          lxc_name: ${{ inputs.lxc_name }}

      - name: Scope PVE vars to current environment
        uses: ./.gitea/actions/normalize-pve-env
        with:
          secrets_json: ${{ toJson(secrets) }}
          vars_json: ${{ toJson(vars) }}
          target_node: ${{ env.LXC_NODE }}

      - name: Lookup LXC IP
        uses: ./.gitea/actions/lookup-lxc-ip
        with:
          lxc_node_ip: ${PVE_NODE_IP}
          vmid: ${LXC_VMID}

      - name: Render hosts.ini
        run: |
          cat > hosts.ini <<EOF
          [lxc]
          ${{ inputs.lxc_name }} ansible_host=${LXC_IP} ansible_user=root

          [all:vars]
          source_host=${{ inputs.source_host }}
          source_user=${{ inputs.source_user }}
          EOF

      - name: Debug hosts.ini
        run: cat hosts.ini

      - name: Run Ansible Playbook
        shell: bash
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: ansible-playbook -i hosts.ini ${{ inputs.playbook }} --vault-password-file <(echo "$ANSIBLE_VAULT_PASSWORD")