name: Run Ansible Migration Playbook

on:
  workflow_call:
    inputs:
      lxc_name:
        description: "Name of the lxc to look migrate to"
        required: true
        type: string
      playbook:
        description: "Absolute path to the ansible playbook to run"
        required: true
        type: string
      source_host:
        description: "IP address of domain name of migration source"
        required: true
        type: string
      source_user:
        description: "User who owns the data to be migrated"
        required: true
        type: string
    secrets: inherit

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Scope PVE vars to current environment
        uses: ./.gitea/actions/normalize-pve-env
        with:
          secrets_json: ${{ toJson(secrets) }}
          vars_json: ${{ toJson(vars) }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MASTER_SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${PVE_NODE_IP} >> ~/.ssh/known_hosts
      
      - name: Lookup LXC VMID and IP
        uses: ./.github/actions/lookup-lxc
        with:
          pve_node_ip: ${PVE_NODE_IP}
          lxc_name: "${{ inputs.lxc_name }}"

      - name: Render hosts.ini
        run: |
          cat > hosts.ini <<EOF
          [lxc]
          ${{ inputs.lxc_name }} ansible_host=${LXC_IP} ansible_user=root

          [all:vars]
          source_host=${{ inputs.source_host }}
          source_user=${{ inputs.source_user }}
          EOF

      - name: debug hosts.ini
        run: cat hosts.ini

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: ansible-playbook -i hosts.ini ${{ inputs.playbook }}