name: common | lxc-template

on:
  workflow_call:
    inputs:
      playbook:
        description: "Path to the template ansible playbook e.g. services/traefik/ansible/traefik-template.yaml"
        required: true
        type: string
      template_name:
        description: "Name for LXC template"
        required: true
        type: string
      lxc_name:
        description: "Name of the lxc to look up"
        required: true
        type: string
      base_template:
        description: "location of the base os template"
        required: true
        type: string
      enable_docker:
        description: "Should keyctl and nesting be enabled in the LXC"
        required: false
        default: "false"
      unprivileged:
        description: "Should lxc be unprivileged"
        required: true
        type: string
      dump_template:
        description: "Whether to dump the LXC to a template file and destroy it afterwards"
        required: false
        type: string
        default: "false"
    secrets: inherit
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Scope PVE vars to current environment
        id: scope-pve
        uses: ./.gitea/actions/scope-pve-env
        with:
          secrets_json: ${{ toJson(secrets) }}
          vars_json: ${{ toJson(vars) }}

      - name: Setup SSH key
        uses: ./.gitea/actions/setup-ssh
        with:
          ssh_private_key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}

      - name: Cleanup any already existing LXC template
        uses: ./.gitea/actions/cleanup-old-lxc-templates
        with:
          lxc_name: ${{ inputs.lxc_name }}-template
          pve_node_ip: ${{ steps.scope-pve.outputs.pve_default_node_ip }}

      - name: Create pve-provider.auto.tfvars
        run: |
          cat > terraform/modules/lxc/pve-provider.auto.tfvars <<EOF
          pm_user         = "${{ steps.scope-pve.outputs.pve_user }}"
          pm_password     = "${{ steps.scope-pve.outputs.pve_password }}"
          pm_api_url      = "${{ steps.scope-pve.outputs.pve_api_url }}"
          EOF

      - name: Lookup environment
        id: lookup-env
        uses: ./.gitea/actions/lookup-env

      - name: Create vars.auto.tfvars
        run: |
          cat > terraform/modules/lxc/vars.auto.tfvars <<EOF
          lxc_password    = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key  = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          gateway         = "${{ vars.GATEWAY }}"
          storage         = "${{ steps.scope-pve.outputs.pve_disk_storage }}"
          ostemplate      = "${{ (steps.lookup-env.outputs.env == 'prod' && 'truenas' || 'local') }}:vztmpl/${{ inputs.base_template }}"
          hostname        = "${{ inputs.lxc_name }}-template"
          enable_docker   = ${{ inputs.enable_docker }}
          unprivileged    = ${{ inputs.unprivileged }}
          target_node     = "${{ steps.scope-pve.outputs.pve_default_node }}"
          EOF

      - name: Terraform Init
        run: terraform -chdir=terraform/modules/lxc init -input=false

      - name: Terraform Plan
        run: terraform -chdir=terraform/modules/lxc plan -out=tfplan -input=false

      - name: Terraform Apply
        run: terraform -chdir=terraform/modules/lxc apply -input=false -auto-approve tfplan

      - name: Lookup LXC VMID and node
        id: lxc
        uses: ./.gitea/actions/lookup-lxc-vmid-node
        with:
          lxc_name: "${{ inputs.lxc_name }}-template"

      # for templates we always use the default node
      - name: Lookup LXC IP
        id: lxc-ip
        uses: ./.gitea/actions/lookup-lxc-ip
        with:
          lxc_node_ip: ${{ steps.scope-pve.outputs.pve_default_node_ip }}
          vmid: ${{ steps.lxc.outputs.vmid }}

      - name: Render hosts.ini
        run: |
          cat > hosts.ini <<EOF
          [lxc]
          ${{ inputs.lxc_name }} ansible_host=${{ steps.lxc-ip.outputs.ip }} ansible_user=root

          [pve_host]
          pve ansible_host=${{ steps.scope-pve.outputs.pve_default_node_ip }} ansible_user=root

          [pve_host:vars]
          vmid=${{ steps.lxc.outputs.vmid }}
          template_name=${{ inputs.template_name }}
          templates_dir=${{ steps.scope-pve.outputs.pve_templates_dir }}
          EOF

      - name: Debug hosts.ini
        run: cat hosts.ini

      - name: Inject ansible dump-to-template task
        if: ${{ inputs.dump_template == 'true' }}
        run: |
          echo "\n- import_playbook: $GITHUB_WORKSPACE/ansible/common/dump-lxc-to-template.yaml" >> ${{ inputs.playbook }}

      - name: Run Ansible Playbook
        shell: bash
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: ansible-playbook -i hosts.ini ${{ inputs.playbook }} --vault-password-file <(echo "$ANSIBLE_VAULT_PASSWORD")

      - name: Terraform Destroy
        if: ${{ inputs.dump_template == 'true' || failure() }}
        run: terraform -chdir=terraform/modules/lxc destroy -auto-approve -input=false

      - name: Stop LXC container
        if: ${{ inputs.dump_template != 'true' && !failure() }}
        run: |
          ssh -oBatchMode=yes root@${{ steps.scope-pve.outputs.pve_default_node_ip }} "
            if pct status ${{ steps.lxc.outputs.vmid }} | grep -q 'status: running'; then
              echo 'Stopping container ${{ steps.lxc.outputs.vmid }}...'
              pct stop ${{ steps.lxc.outputs.vmid }}
            else
              echo 'Container ${{ steps.lxc.outputs.vmid }} is already stopped.'
            fi
          "