name: common | post-deploy

on:
  workflow_call:
    inputs:
      lxc_name:
        description: "Name of the LXC to ensure is running"
        required: true
        type: string
    secrets: inherit

jobs:
  post-deploy:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: ./.gitea/actions/setup-ssh
        with:
          ssh_private_key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}

      - name: Lookup LXC VMID and node
        uses: ./.gitea/actions/lookup-lxc-vmid-node
        with:
          lxc_name: ${{ inputs.lxc_name }}

      - name: Scope PVE vars to current environment
        uses: ./.gitea/actions/normalize-pve-env
        with:
          secrets_json: ${{ toJson(secrets) }}
          vars_json: ${{ toJson(vars) }}
          target_node: ${{ env.LXC_NODE }}

      - name: Lookup LXC IP
        uses: ./.gitea/actions/lookup-lxc-ip
        with:
          lxc_node_ip: ${PVE_NODE_IP}
          vmid: ${LXC_VMID}

      - name: Ensure LXC is running
        run: ssh -oBatchMode=yes root@${PVE_NODE_IP} "pct start ${LXC_VMID} || true"

      - name: Sleep to allow LXC to come online
        run: sleep 15