name: common | lxc-terraform

on:
  workflow_call:
    inputs:
      target_node:
        description: "Name for PVE node to deploy on"
        required: true
        type: string
      lxc_name:
        description: "Hostname of the LXC"
        required: true
        type: string
      base_template:
        description: "name of the base os template"
        required: true
        type: string
      vmid:
        description: "VMID for the LXC"
        required: true
        type: string
      ip:
        description: "IP address for the LXC"
        required: true
        type: string
      memory:
        description: "Memory in MB for the LXC"
        required: true
        type: string
      cores:
        description: "Number of cores for the LXC"
        required: true
        type: string
      storage_size:
        description: "Size of the LXC disk e.g. 16G"
        required: true
        type: string
      enable_docker:
        description: "Should keyctl and nesting be enabled so docker can run"
        required: true
        type: string
      unprivileged:
        description: "should lxc be unprivileged"
        required: true
        type: string
    secrets: inherit

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Scope AWS vars to current environment
        uses: ./.gitea/actions/normalize-aws-env
        with:
          secrets_json: ${{ toJson(secrets) }}
          vars_json: ${{ toJson(vars) }}

      - name: Scope PVE vars to current environment
        uses: ./.gitea/actions/normalize-pve-env
        with:
          secrets_json: ${{ toJson(secrets) }}
          vars_json: ${{ toJson(vars) }}
          target_node: ${{ github.ref_name == 'main' && inputs.target_node || vars.PVE_DEFAULT_TARGET_NODE_DEV }}

      - name: Create pve-provider.auto.tfvars
        run: |
          cat > terraform/modules/lxc/pve-provider.auto.tfvars <<EOF
          pm_user         = "${PVE_USER}"
          pm_password     = "${PVE_PASSWORD}"
          pm_api_url      = "${PVE_API_URL}"
          EOF

      - name: Create vars.auto.tfvars
        run: |
          cat > terraform/modules/lxc/vars.auto.tfvars <<EOF
          lxc_password   = "${{ secrets.LXC_PASSWORD }}"
          ssh_public_key = "${{ secrets.MASTER_SSH_PUBLIC_KEY }}"
          gateway        = "${{ vars.GATEWAY }}"
          storage        = "${PVE_DISK_STORAGE}"
          target_node    = "${{ github.ref_name == 'main' && inputs.target_node || env.PVE_DEFAULT_TARGET_NODE }}"
          hostname       = "${{ inputs.lxc_name }}"
          ostemplate     = "${{ (github.ref_name == 'main' && 'truenas' || 'local') }}:vztmpl/${{ inputs.base_template }}"
          vmid           = "${{ inputs.vmid }}"
          ip             = "${{ inputs.ip }}"
          memory         = ${{ inputs.memory }}
          cores          = ${{ inputs.cores }}
          storage_size   = "${{ inputs.storage_size }}"
          enable_docker  = ${{ inputs.enable_docker }}
          unprivileged   = ${{ inputs.unprivileged }}
          EOF

      - name: Generate backend.tf
        run: |
          cat > terraform/modules/lxc/backend.tf <<EOF
          terraform {
            backend "s3" {
              bucket = "${AWS_TF_BACKEND_BUCKET}"
              region = "${{ vars.AWS_REGION }}"
              key    = "${{ inputs.lxc_name }}.tfstate"
            }
          }
          EOF

      - name: Debug backend.tf
        run: cat terraform/modules/lxc/backend.tf

      - name: Terraform Init
        run: terraform -chdir=terraform/modules/lxc init -input=false

      - name: Terraform Refresh
        run: terraform -chdir=terraform/modules/lxc refresh -input=false

      - name: Terraform Plan
        run: terraform -chdir=terraform/modules/lxc plan -out=tfplan -input=false

      - name: Terraform Apply
        if: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) }}
        run: terraform -chdir=terraform/modules/lxc apply -input=false -auto-approve tfplan