name: services | jellyfin-ombi | lxc

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - ".gitea/workflows/services/jellyfin-ombi/lxc.yaml"
  workflow_dispatch:
    inputs:
      force:
        description: "Pass 'true' to force apply and post-deploy steps to run"
        required: false
        type: string

jobs:
  deploy:
    uses: ./.gitea/workflows/common/lxc-terraform.yaml
    with:
      target_node: "mother"
      lxc_name: jellyfin-ombi
      base_template: jellyfin-ombi-debian12.tar.gz
      vmid: "302"
      ip: ${{ github.ref_name == 'main' && '10.1.1.21/24' || '10.1.1.121/24' }}
      memory: "4096"
      cores: "2"
      storage_size: "16G"
      enable_docker: false
      unprivileged: true
      apply: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) || inputs.force == 'true' }}
    secrets: inherit
  
  wait-for-boot:
    needs: deploy
    if: ${{ needs.deploy.outputs.created == 'true' || inputs.force == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}
    steps:
      - name: Sleep to allow LXC to boot
        run: sleep 15
       
  add-media-mount:
    needs: wait-for-boot
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/common/add-unprivileged-nfs-mount.yaml
    secrets: inherit

  add-cattle-share-mount:
    needs: wait-for-boot
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/common/add-cattle-share.yaml
    secrets: inherit

  add-backup-mount:
      needs: wait-for-boot
      uses: ./.gitea/workflows/common/lxc-ansible.yaml
      with:
        lxc_name: jellyfin-ombi
        playbook: ansible/common/add-backups-mount.yaml
        extra_vars: "env=${{ github.ref_name == 'main' && 'prod' || 'dev' }}"
      secrets: inherit

  add-igpu-passthrough:
    needs: wait-for-boot
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/common/add-igpu-passthrough.yaml
    secrets: inherit