name: services | jellyfin-ombi | lxc

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - ".gitea/workflows/services/jellyfin-ombi/lxc.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/common/lxc-terraform.yaml
    with:
      target_node: "mother"
      lxc_name: jellyfin-ombi
      base_template: jellyfin-ombi-debian12.tar.gz
      vmid: "302"
      ip: "10.1.1.21/24"
      memory: "4096"
      cores: "2"
      storage_size: "16G"
      enable_docker: false
      unprivileged: true
    secrets: inherit
  
  post-deploy:
    needs: deploy
    uses: ./.gitea/workflows/common/lxc-post-deploy.yaml
    with:
      vmid: "302"
    secrets: inherit
       
  add-media-mount:
    if: ${{ contains(fromJSON('["main"]'), github.ref_name) }}
    needs: post-deploy
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/common/add-unprivileged-nfs-mount.yaml
    secrets: inherit

  add-cattle-share-mount:
    if: ${{ contains(fromJSON('["main", "dev"]'), github.ref_name) }}
    needs: post-deploy
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/common/add-cattle-share.yaml
    secrets: inherit

  add-igpu-passthrough:
    if: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) }}
    needs: post-deploy
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/common/add-igpu-passthrough.yaml
    secrets: inherit