name: services | jellyfin-ombi | migration

on:
  workflow_dispatch:

jobs:
  jellyfin-migration:
    uses: ./.gitea/workflows/common/lxc-migration.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: services/jellyfin-ombi/ansible/jellyfin-migration.yaml
      source_host: "10.1.1.63"
      source_user: root
    secrets: inherit
  ombi-migration:
    uses: ./.gitea/workflows/common/lxc-migration.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: services/jellyfin-ombi/ansible/ombi-migration.yaml
      source_host: "10.1.1.61"
      source_user: dietpi
    secrets: inherit