name: services | jellyfin-ombi | template

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - "services/jellyfin-ombi/ansible/jellyfin-ombi-template.yaml"
      - ".gitea/workflows/services/jellyfin-ombi/template.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/common/lxc-template.yaml
    with:
      playbook: services/jellyfin-ombi/ansible/jellyfin-ombi-template.yaml
      lxc_name: jellyfin-ombi
      template_name: jellyfin-ombi-debian12
      base_template: debian-12-standard_12.12-1_amd64.tar.zst
      enable_docker: false
      unprivileged: true
      dump_template: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) }}
    secrets: inherit