name: Arr Migration from Docker to LXC CI/CD

on:
  workflow_dispatch:

jobs:
  migration:
    uses: ./.gitea/workflows/lxc-migration.yaml
    with:
      lxc_name: arr
      playbook: ansible/arr/arr-migration.yaml
      source_host: "10.1.1.61"
      source_user: dietpi
    secrets: inherit