name: Arr stack LXC template CI/CD

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - "ansible/arr/arr-template.yaml"
      - "ansible/arr/docker-compose.yaml"
      - ".gitea/workflows/arr/arr-template.yaml"
  workflow_dispatch:

jobs:
  create-template:
    uses: ./.gitea/workflows/common/lxc-template.yaml
    with:
      lxc_name: arr
      template_name: arr-debian12
      ostemplate: truenas:vztmpl/docker-debian12.tar.gz
      enable_docker: true
      unprivileged: true
    secrets: inherit