- name: Mount nfs on host node to unprivileged LXC
  hosts: pve_host
  become: yes
  tasks:
    - name: Check if mp1 is already configured
      command: pct config {{ vmid }}
      register: pct_config
      changed_when: false

    - name: Add mount point
      command: pct set {{ vmid }} -mp1 /mnt/cattle_share,mp=/mnt/cattle_share,replicate=0
      when: "'mp1: /mnt/cattle_share,mp=/mnt/cattle_share,replicate=0' not in pct_config.stdout"