name: services | music | update

on:
  workflow_dispatch:

jobs:
  update:
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: music
      playbook: ansible/common/update-docker-lxc.yaml
    secrets: inherit