name: Jellyfin LXC and Ombi Docker Migration to LXC CI/CD

on:
  workflow_dispatch:

jobs:
  jellyfin-migration:
    uses: ./.gitea/workflows/common/lxc-migration.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/jellyfin-ombi/jellyfin-migration.yaml
      source_host: "10.1.1.63"
      source_user: root
    secrets: inherit
  ombi-migration:
    uses: ./.gitea/workflows/common/lxc-migration.yaml
    with:
      lxc_name: jellyfin-ombi
      playbook: ansible/jellyfin-ombi/ombi-migration.yaml
      source_host: "10.1.1.61"
      source_user: dietpi
    secrets: inherit