services:
  hdro:
    subdomain: hdro
    port: 8080
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.206
        dev_ip: 10.1.1.206

  jellyfin:
    subdomain: jellyfin
    port: 8096
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.21
        dev_ip: 10.1.1.121

  ombi:
    subdomain: ombi
    port: 5000
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.21
        dev_ip: 10.1.1.121

  prowlarr:
    subdomain: prowlarr
    port: 9696
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.20
        dev_ip: 10.1.1.120

  sonarr:
    subdomain: sonarr
    port: 8989
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.20
        dev_ip: 10.1.1.120

  radarr:
    subdomain: radarr
    port: 7878
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.20
        dev_ip: 10.1.1.120

  sabnzbd:
    subdomain: sabnzbd
    port: 8084
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.20
        dev_ip: 10.1.1.120

  wiki:
    subdomain: wiki
    port: 3000
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.64
        dev_ip: 10.1.1.164

  git:
    subdomain: git
    port: 3000
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.65
        dev_ip: 10.1.1.165

  dns:
    subdomain: dns
    port: 5380
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.5
        dev_ip: 10.1.1.5

  airflow:
    subdomain: airflow
    port: 8080
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.30
        dev_ip: 10.1.1.130

  kafka:
    subdomain: kafka
    port: 8080
    middleware: chain-authelia@file
    servers:
      - prod_ip: 10.1.1.11
        dev_ip: 10.1.1.111
      - prod_ip: 10.1.1.12
        dev_ip: 10.1.1.112
      - prod_ip: 10.1.1.13
        dev_ip: 10.1.1.113