name: Docker LXC template CI/CD

on:
  push:
    branches:
      - main
      - "feature/**"
    paths:
      - "ansible/docker/docker-template.yaml"
      - ".gitea/workflows/docker/docker-template.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/common/lxc-template.yaml
    with:
      lxc_name: docker
      template_name: docker-debian12
      base_template: debian-12-standard_12.12-1_amd64.tar.zst
      unprivileged: true
    secrets: inherit