name: Postgres17 LXC template CI/CD

on:
  push:
    branches:
      - main
      - "feature/**"
    paths:
      - "ansible/postgres17/postgres17-template.yaml"
      - ".gitea/workflows/postgres17/postgres17-template.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/common/lxc-template.yaml
    with:
      lxc_name: postgres17
      template_name: postgres17-debian12
      base_template: debian-12-standard_12.12-1_amd64.tar.zst
      unprivileged: true
    secrets: inherit
