name: services | torrents | backup

on:
  workflow_dispatch:

jobs:
  backup:
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/backup-appdata.yaml
    secrets: inherit