name: services | torrents | lxc

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - ".gitea/workflows/services/torrents/lxc.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/common/lxc-terraform.yaml
    with:
      target_node: "mother"
      lxc_name: torrents
      base_template: docker-debian12.tar.gz
      vmid: "304"
      ip: ${{ github.ref_name == 'main' && '10.1.1.22/24' || '10.1.1.122/24' }}
      memory: "2048"
      cores: "1"
      storage_size: "16G"
      enable_docker: true
      unprivileged: true
      apply: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) == 'false' }}
      # apply: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) }}
    secrets: inherit

  wait-for-boot:
    needs: deploy
    if: ${{ needs.deploy.outputs.created == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}
    steps:
      - name: Sleep to allow LXC to boot
        run: sleep 15

  setup:
    needs: wait-for-boot
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: services/torrents/ansible/torrents-setup.yaml
    secrets: inherit

  add-media-mount:
    needs: wait-for-boot
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/add-unprivileged-nfs-mount.yaml
    secrets: inherit

  add-tun-device:
    needs: wait-for-boot
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/add-tun-device.yaml
    secrets: inherit

  start-containers:
    needs: [setup, add-media-mount, add-tun-device]
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/start-docker-containers.yaml
    secrets: inherit