name: services | torrents | lxc

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - ".gitea/workflows/services/torrents/lxc.yaml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.gitea/workflows/common/lxc-terraform.yaml
    with:
      target_node: "mother"
      lxc_name: torrents
      base_template: torrents-debian12.tar.gz
      vmid: "304"
      ip: ${{ github.ref_name == 'main' && '10.1.1.22/24' || '10.1.1.122/24' }}
      memory: "2048"
      cores: "1"
      storage_size: "16G"
      enable_docker: true
      unprivileged: true
      apply: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) }}
    secrets: inherit

  post-deploy:
    needs: deploy
    if: ${{ needs.deploy.outputs.applied == 'true' }}
    uses: ./.gitea/workflows/common/lxc-post-deploy.yaml
    with:
      lxc_name: torrents
    secrets: inherit

  add-media-mount:
    needs: [deploy, post-deploy]
    if: ${{ needs.deploy.outputs.applied == 'true' }}
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/add-unprivileged-nfs-mount.yaml
    secrets: inherit

  add-tun-device:
    needs: [deploy, post-deploy]
    if: ${{ needs.deploy.outputs.applied == 'true' }}
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/add-tun-device.yaml
    secrets: inherit

  inject-env:
    needs: [deploy, post-deploy]
    if: ${{ needs.deploy.outputs.applied == 'true' }}
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: services/torrents/ansible/torrents-inject-env.yaml
    secrets: inherit

  start-containers:
    needs: [deploy, add-media-mount, add-tun-device, inject-env]
    if: ${{ needs.deploy.outputs.applied == 'true' }}
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/start-docker-containers.yaml
    secrets: inherit