name: services | torrents | template

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - "services/torrents/ansible/torrents-template.yaml"
      - "services/torrents/docker-compose.yaml"
      - "services/torrents/config/**"
      - ".gitea/workflows/services/torrents/template.yaml"
  workflow_dispatch:

jobs:
  create-template:
    uses: ./.gitea/workflows/common/lxc-template.yaml
    with:
      playbook: services/torrents/ansible/torrents-template.yaml
      lxc_name: torrents
      template_name: torrents-debian12
      base_template: docker-debian12.tar.gz
      enable_docker: true
      unprivileged: true
      dump_template: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) }}
    secrets: inherit