name: services | torrents | update-config

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "services/torrents/docker-compose.yaml"
      - "services/torrents/config/categories.json"
      - "services/torrents/ansible/vault.yaml"
      - "services/torrents/ansible/torrents-setup.yaml"
  workflow_dispatch:

jobs:
  start-lxc:
    uses: ./.gitea/workflows/common/lxc-start.yaml
    with:
      lxc_name: torrents
    secrets: inherit

  setup:
    needs: start-lxc
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      # Will not overwrite config (avoids password reset)
      playbook: services/torrents/ansible/torrents-setup.yaml
    secrets: inherit

  restart-containers:
    needs: setup
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: torrents
      playbook: ansible/common/start-docker-containers.yaml
    secrets: inherit