name: services | ombi | update

on:
  workflow_dispatch:

jobs:
  start-lxc:
    uses: ./.gitea/workflows/common/lxc-start.yaml
    with:
      lxc_name: ombi
    secrets: inherit

  update:
    needs: start-lxc
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: ombi
      playbook: ansible/common/update-docker-lxc.yaml
    secrets: inherit