name: Traefik LXC template CI/CD

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - "ansible/traefik/traefik-template.yaml"
      - "ansible/traefik/docker-compose.yaml"
      - ".gitea/workflows/traefik/traefik-template.yaml"
  workflow_dispatch:

jobs:
  create-template:
    uses: ./.gitea/workflows/common/lxc-template.yaml
    with:
      lxc_name: traefik
      template_name: traefik-debian12
      base_template: docker-debian12.tar.gz
      enable_docker: true
      unprivileged: true
    secrets: inherit
    