---
- name: Setup torrents LXC
  hosts: lxc
  become: yes
  vars_files:
    - vault.yaml
  vars:
    remote_dir: /docker
    service_dir: "{{ playbook_dir }}/.."
    qbit_config_dir: /docker/appdata/qbittorrent/qBittorrent

  tasks:
    - name: Ensure docker directory exists
      file:
        path: "{{ remote_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure qBittorrent config directory exists
      file:
        path: "{{ qbit_config_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yaml
      copy:
        src: "{{ service_dir }}/docker-compose.yaml"
        dest: "{{ remote_dir }}/docker-compose.yaml"
        owner: root
        group: root
        mode: '0644'

    - name: Copy qBittorrent.conf
      copy:
        src: "{{ service_dir }}/config/qBittorrent.conf"
        dest: "{{ qbit_config_dir }}/qBittorrent.conf"
        owner: root
        group: root
        mode: '0644'
        force: no

    - name: Copy categories.json
      copy:
        src: "{{ service_dir }}/config/categories.json"
        dest: "{{ qbit_config_dir }}/categories.json"
        owner: root
        group: root
        mode: '0644'
        force: no

    - name: Render .env file from vault
      copy:
        dest: "{{ remote_dir }}/.env"
        mode: "0600"
        content: |
          VPN_SERVICE_PROVIDER={{ VPN_SERVICE_PROVIDER }}
          VPN_TYPE={{ VPN_TYPE }}
          OPENVPN_USER={{ OPENVPN_USER }}
          OPENVPN_PASSWORD={{ OPENVPN_PASSWORD }}
          SERVER_COUNTRIES={{ SERVER_COUNTRIES }}