name: services | kafka | lxc

on:
  push:
    branches:
      - main
      - dev
      - "release/**"
      - "feature/**"
    paths:
      - ".gitea/workflows/services/kafka/lxc.yaml"
      - "services/kafka/docker-compose.yaml.j2"
  workflow_dispatch:
    inputs:
      force:
        description: "Pass 'true' to force apply and post-deploy steps to run"
        required: false
        type: string

jobs:
  deploy-broker-1:
    uses: ./.gitea/workflows/common/lxc-terraform.yaml
    with:
      target_node: "mother"
      lxc_name: kafka-1
      base_template: docker-debian12.tar.gz
      vmid: "310"
      ip: ${{ github.ref_name == 'main' && '10.1.1.11/24' || '10.1.1.111/24' }}
      memory: "2048"
      cores: "1"
      storage_size: "32G"
      enable_docker: true
      unprivileged: true
      apply: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) || inputs.force == 'true' }}
    secrets: inherit

  deploy-broker-2:
    uses: ./.gitea/workflows/common/lxc-terraform.yaml
    with:
      target_node: "fish"
      lxc_name: kafka-2
      base_template: docker-debian12.tar.gz
      vmid: "311"
      ip: ${{ github.ref_name == 'main' && '10.1.1.12/24' || '10.1.1.112/24' }}
      memory: "2048"
      cores: "1"
      storage_size: "32G"
      enable_docker: true
      unprivileged: true
      apply: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) || inputs.force == 'true' }}
    secrets: inherit

  deploy-broker-3:
    uses: ./.gitea/workflows/common/lxc-terraform.yaml
    with:
      target_node: "fastfood"
      lxc_name: kafka-3
      base_template: docker-debian12.tar.gz
      vmid: "312"
      ip: ${{ github.ref_name == 'main' && '10.1.1.13/24' || '10.1.1.113/24' }}
      memory: "2048"
      cores: "1"
      storage_size: "32G"
      enable_docker: true
      unprivileged: true
      apply: ${{ contains(fromJSON('["main","dev"]'), github.ref_name) || inputs.force == 'true' }}
    secrets: inherit

  wait-for-boot:
    needs: [deploy-broker-1, deploy-broker-2, deploy-broker-3]
    if: ${{ needs.deploy-broker-1.outputs.created == 'true' || inputs.force == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.RUNNER_IMAGE }}
    steps:
      - name: Sleep to allow LXC to boot
        run: sleep 15
  
  # Safe/idempotent
  configure:
    needs: wait-for-boot
    uses: ./.gitea/workflows/common/lxc-3-node-ansible.yaml
    with:
      playbook: services/kafka/ansible/kafka-setup.yaml
      service_name: kafka
    secrets: inherit
