name: services | kafka | update-config

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "services/kafka/docker-compose.yaml"
      - "services/kafka/ansible/kafka-setup.yaml"
  workflow_dispatch:

jobs:
  start-lxc-1:
    uses: ./.gitea/workflows/common/lxc-post-deploy.yaml
    with:
      lxc_name: kafka-1
    secrets: inherit
  start-lxc-2:
    uses: ./.gitea/workflows/common/lxc-post-deploy.yaml
    with:
      lxc_name: kafka-2
    secrets: inherit
  start-lxc-3:
    uses: ./.gitea/workflows/common/lxc-post-deploy.yaml
    with:
      lxc_name: kafka-3
    secrets: inherit

  configure:
    needs: [start-lxc-1, start-lxc-2, start-lxc-3]
    uses: ./.gitea/workflows/common/lxc-3-node-ansible.yaml
    with:
      playbook: services/kafka/ansible/kafka-setup.yaml
      service_name: kafka
    secrets: inherit