name: services | jellyfin | update

on:
  workflow_dispatch:

jobs:
  start-lxc:
    uses: ./.gitea/workflows/common/lxc-start.yaml
    with:
      lxc_name: jellyfin
    secrets: inherit

  update:
    needs: start-lxc
    uses: ./.gitea/workflows/common/lxc-ansible.yaml
    with:
      lxc_name: jellyfin
      playbook: ansible/common/apt-upgrade.yaml
    secrets: inherit