http:
  routers:
{%- for name, svc in services.items() %}
    {{ name }}-router:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`{{ svc.subdomain }}.{{ DOMAIN }}`)"
      service: {{ name }}-service
      middlewares:
        - {{ svc.middleware }}
{%- endfor %}

  services:
{%- for name, svc in services.items() %}
    {{ name }}-service:
      loadBalancer:
        servers:
{%- for server in svc.servers %}
          - url: "http://{% if env == 'dev' %}{{ server.dev_ip }}{% else %}{{ server.prod_ip }}{% endif %}:{{ svc.port }}"
{%- endfor %}
{%- endfor %}

tcp:
  routers:
    git-ssh-router:
      entryPoints:
        - "ssh"
      rule: "HostSNI(`*`)"
      service: git-ssh-service
      middlewares:
        - allow-ssh@file

  services:
    git-ssh-service:
      loadBalancer:
        servers:
          - address: "{% if env == 'dev' %}{{ services.git.dev_ip }}{% else %}{{ services.git.prod_ip }}{% endif %}:22"